version: '3.9'

services:
  backend:
    build:
      context: ./notes_app
      dockerfile: Dockerfile
    container_name: django_backend
    restart: always
    volumes:
      - ./notes_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: notes
      DB_USER: root
      DB_PASSWORD: 123456

  frontend:
    build:
      context: ./daily-note
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    ports:
      - "3000:80"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: notes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
